import Head from "next/head";
import {gql} from "@apollo/client";
import {client} from "../lib/apollo";

// Components
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Awards from "../components/Awards";
import ReadBlogs from "../components/ReadBlogs";
import CaseStudies from "../components/CaseStudies";
import Testimonial from "../components/Testimonial";
import TextImageJumbo from "../components/TextImageJumbo";
import ContentSquares from "../components/ContentSquares";
import TitleAndParagraph from "../components/TitleAndParagraph.js";

export default function Home({
	pageTitle,
	navbarContent,
	navbarMenu,
	homePageContent,
	caseStudiesContent,
	readBlogsContent,
	footerContent,
	footerMenu,
}) {
	return (
		<>
			<Head>
				<title>{pageTitle}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/svg/favicon.svg" />
			</Head>

			{/* <!--===== NAVBAR =====--> */}
			<Navbar navbarContent={navbarContent} menuLinks={navbarMenu} />

			<main>
				{/* HERO */}
				<Hero
					title={homePageContent?.heroSection?.title}
					backgroundImage={homePageContent?.heroSection?.heroImage?.sourceUrl}
				/>

				{/* TITLE AND PARAGRAPH */}
				<TitleAndParagraph
					// Content
					title={homePageContent?.titleTwoParagraphsButton?.title}
					boldParagraph={
						homePageContent?.titleTwoParagraphsButton?.boldParagraph
					}
					paragraphOne={homePageContent?.titleTwoParagraphsButton?.paragraphOne}
					paragraphTwo={homePageContent?.titleTwoParagraphsButton?.paragraphTwo}
					buttonLink={homePageContent?.titleTwoParagraphsButton?.buttonLink}
					// Display Options
					displayThreeSquaresOption={
						homePageContent?.titleTwoParagraphsButton?.displayThreeSquaresOption
					}
					displayEmailLinkOption={
						homePageContent?.titleTwoParagraphsButton?.displayEmailLinkOption
					}
					displayButtonOption={
						homePageContent?.titleTwoParagraphsButton?.displayButtonOption
					}
					displayBoldText={
						homePageContent?.titleTwoParagraphsButton?.displayBoldText
					}
				/>

				{/* CONTENT SQUARES */}
				<ContentSquares
					// Content
					title={homePageContent?.contentSquares?.title}
					columnOne={homePageContent?.contentSquares?.column}
					columnTwo={homePageContent?.contentSquares?.columnTwo}
					columnThree={homePageContent?.contentSquares?.columnThree}
					columnFour={homePageContent?.contentSquares?.columnFour}
					// Display Options
					displayTitle={homePageContent?.contentSquares?.displayTitle}
					displayNumberOfColumns={
						homePageContent?.contentSquares?.displayNumberOfColumns
					}
					// Display Squares (Blue/Grey)
					displayBlueGreySquares={
						homePageContent?.contentSquares?.displayBlueGreySquares
					}
					// Display Background Squares Aesthetics
					displayBackgroundAesthetics={
						homePageContent?.contentSquares?.displayBackgroundAesthetics
					}
				/>

				{/* TEXT & IMAGE JUMBO SECTION */}
				<TextImageJumbo
					contentSectionOne={homePageContent?.textImageJumbo?.textImageGroupOne}
					contentSectionTwo={homePageContent?.textImageJumbo?.textImageGroupTwo}
					contentSectionThree={
						homePageContent?.textImageJumbo?.textImageGroupThree
					}
				/>

				{/* CASE STUDIES */}
				<CaseStudies
					title={homePageContent?.caseStudies?.title}
					paragraph={homePageContent?.caseStudies?.paragraph}
					caseStudiesContent={caseStudiesContent}
				/>

				{/* TESTIMONIAL */}
				<Testimonial
					// Content
					title={homePageContent?.testimonialSlider?.title}
					testimonialContent={
						homePageContent?.testimonialSlider?.testimonialContent
					}
					// Display Options
					displayBackgroundAesthetics={
						homePageContent?.testimonialSlider?.displayBackgroundAesthetics
					}
				/>

				{/* AWARDS */}
				<Awards
					title={homePageContent?.awards?.title}
					buttonLink={homePageContent?.awards?.buttonLink}
					paragraphOne={homePageContent?.awards?.paragraphOne}
					paragraphTwo={homePageContent?.awards?.paragraphTwo}
					awardsOneImage={homePageContent?.awards?.awardsOne?.sourceUrl}
					awardsTwoImage={homePageContent?.awards?.awardsTwo?.sourceUrl}
					// Display Options
					displayStylingOptions={homePageContent?.awards?.displayStylingOptions}
					displayButtonOptions={homePageContent?.awards?.displayButtonOptions}
					selectBackgroundAestheticsOptions={
						homePageContent?.awards?.selectBackgroundAestheticsOptions
					}
				/>

				{/* READ BLOGS */}
				<ReadBlogs
					title={homePageContent?.readOurBlogsTitle}
					readBlogsContent={readBlogsContent}
				/>
			</main>

			{/* <!--===== FOOTER =====--> */}
			<Footer footerContent={footerContent} menuLinks={footerMenu} />
		</>
	);
}

export async function getStaticProps() {
	const getHomePageContent = gql`
		{
			mainContent: pages(where: {id: 7}) {
				edges {
					node {
						homePage {
							titleTwoParagraphsButton {
								title
								paragraphTwo
								paragraphOne
								displayThreeSquaresOption
								displayEmailLinkOption
								displayButtonOption
								displayBoldText
								boldParagraph
								buttonLink {
									url
									title
									target
								}
							}
							textImageJumbo {
								textImageGroupTwo {
									title
									subtitle
									paragraphTwo
									paragraphOne
									image {
										sourceUrl
									}
									buttonLink {
										url
										title
										target
									}
								}
								textImageGroupThree {
									title
									subtitle
									paragraphTwo
									paragraphOne
									buttonLink {
										url
										title
										target
									}
									image {
										sourceUrl
									}
								}
								textImageGroupOne {
									title
									subtitle
									paragraphTwo
									paragraphOne
									buttonLink {
										url
										title
										target
									}
									image {
										sourceUrl
									}
								}
							}
							testimonialSlider {
								title
								displayBackgroundAestheticsOption
								testimonialContent {
									personName
									paragraph
								}
							}
							readOurBlogsTitle
							heroSection {
								title
								heroImage {
									sourceUrl
								}
							}
							contentSquares {
								title
								displayTitle
								displayNumberOfColumns
								displayBlueGreySquares
								displayBackgroundAesthetics
								column {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
								columnTwo {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
								columnThree {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
								columnFour {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
							}
							caseStudies {
								title
								paragraph
							}
							awards {
								title
								selectBackgroundAestheticsOptions
								paragraphTwo
								paragraphOne
								displayStylingOptions
								displayButtonOptions
								buttonLink {
									url
									title
									target
								}
								awardsTwo {
									sourceUrl
								}
								awardsOne {
									sourceUrl
								}
							}
						}
					}
				}
			}
			themesOptions(
				where: {id: 1604, status: PUBLISH, name: "Themes Options"}
			) {
				edges {
					node {
						themesOptions {
							siteTitle
							twitterLink
							phoneNumber
							linkedinLink
							email
							emailOptionTwo
							contactAddress
							contactPostcode
							contactPostcodeText
							phoneNumberOptionTwo
							companyLogo {
								sourceUrl
							}
						}
					}
				}
			}
			serviceMenuLinks: menuItems(where: {location: SERVICES}) {
				edges {
					node {
						url
						label
					}
				}
			}
			aboutMenuLinks: menuItems(where: {location: ABOUT}) {
				edges {
					node {
						url
						label
					}
				}
			}
			remainingMenuLinks: menuItems(where: {location: PRIMARY}) {
				edges {
					node {
						url
						label
					}
				}
			}
			footerMenuLinks: menuItems(where: {location: FOOTER}) {
				edges {
					node {
						url
						label
					}
				}
			}
			caseStudies: caseStudies(
				where: {orderby: {field: DATE, order: DESC}, status: PUBLISH}
				first: 3
			) {
				edges {
					node {
						title
						link
						content(format: RENDERED)
						featuredImage {
							node {
								sourceUrl
							}
						}
					}
				}
			}
			readBlogsContent: posts(
				where: {orderby: {field: DATE, order: DESC}, status: PUBLISH}
				first: 4
			) {
				edges {
					node {
						title
						link
						featuredImage {
							node {
								sourceUrl
							}
						}
						content(format: RENDERED)
					}
				}
			}
		}
	`;

	const response = await client.query({
		query: getHomePageContent,
	});

	return {
		props: {
			pageTitle:
				response?.data?.themesOptions?.edges[0]?.node?.themesOptions?.siteTitle,
			navbarContent:
				response?.data?.themesOptions?.edges[0]?.node?.themesOptions,
			navbarMenu: [
				response?.data?.serviceMenuLinks?.edges,
				response?.data?.aboutMenuLinks?.edges[0],
				response?.data?.remainingMenuLinks?.edges,
			],
			homePageContent: response?.data?.mainContent?.edges[0]?.node?.homePage,
			caseStudiesContent: response.data?.caseStudies?.edges,
			readBlogsContent: response?.data?.readBlogsContent?.edges,
			footerContent:
				response?.data?.themesOptions?.edges[0]?.node?.themesOptions,
			footerMenu: response?.data?.footerMenuLinks?.edges,
		},
		revalidate: 1,
	};
}
