import Head from "next/head";
import {gql} from "@apollo/client";
import {client} from "../lib/apollo";
import {getNavbarContent} from "../lib/navbarContent";
import {getFooterContent} from "../lib/footerContent";
import {getReadBlogsContent} from "../lib/readBlogsContent";
import {getCaseStudiesContent} from "../lib/caseStudiesContent";

// Components
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Awards from "../components/Awards";
import ReadBlogs from "../components/ReadBlogs";
import CaseStudies from "../components/CaseStudies";
import Testimonial from "../components/Testimonial";
import TextImageJumbo from "../components/TextImageJumbo";
import ContentSquares from "../components/ContentSquares";
import TitleTwoParagraphButton from "../components/TitleTwoParagraphButton.js";

export default function Home({
	navbarContent,
	homePageContent,
	caseStudiesContent,
	readBlogsContent,
	footerContent,
}) {
	return (
		<>
			<Head>
				<title>{navbarContent?.pageTitle}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/svg/favicon.svg" />
			</Head>

			{/* <!--===== NAVBAR =====--> */}
			<Navbar
				navbarContent={navbarContent?.navbarContent}
				menuLinks={navbarContent?.navbarMenu}
			/>

			<main>
				{/* HERO */}
				<Hero
					title={homePageContent?.heroSection?.title}
					backgroundImage={homePageContent?.heroSection?.heroImage?.sourceUrl}
				/>

				{/* TITLE AND PARAGRAPH */}
				<TitleTwoParagraphButton
					// Content
					title={homePageContent?.titleTwoParagraphsButton?.title}
					boldParagraph={
						homePageContent?.titleTwoParagraphsButton?.boldParagraph
					}
					paragraphOne={homePageContent?.titleTwoParagraphsButton?.paragraphOne}
					paragraphTwo={homePageContent?.titleTwoParagraphsButton?.paragraphTwo}
					buttonLink={homePageContent?.titleTwoParagraphsButton?.buttonLink}
					// Display Options
					displayThreeSquaresOption={
						homePageContent?.titleTwoParagraphsButton?.displayThreeSquaresOption
					}
					displayEmailLinkOption={
						homePageContent?.titleTwoParagraphsButton?.displayEmailLinkOption
					}
					displayButtonOption={
						homePageContent?.titleTwoParagraphsButton?.displayButtonOption
					}
					displayBoldText={
						homePageContent?.titleTwoParagraphsButton?.displayBoldText
					}
				/>

				{/* CONTENT SQUARES */}
				<ContentSquares
					// Content
					title={homePageContent?.contentSquares?.title}
					columnOne={homePageContent?.contentSquares?.column}
					columnTwo={homePageContent?.contentSquares?.columnTwo}
					columnThree={homePageContent?.contentSquares?.columnThree}
					columnFour={homePageContent?.contentSquares?.columnFour}
					// Display Options
					displayTitle={homePageContent?.contentSquares?.displayTitle}
					displayNumberOfColumns={
						homePageContent?.contentSquares?.displayNumberOfColumns
					}
					// Display Squares (Blue/Grey)
					displayBlueGreySquares={
						homePageContent?.contentSquares?.displayBlueGreySquares
					}
					// Display Background Squares Aesthetics
					displayBackgroundAesthetics={
						homePageContent?.contentSquares?.displayBackgroundAesthetics
					}
				/>

				{/* TEXT & IMAGE JUMBO SECTION */}
				<TextImageJumbo
					contentSectionOne={homePageContent?.textImageJumbo?.textImageGroupOne}
					contentSectionTwo={homePageContent?.textImageJumbo?.textImageGroupTwo}
					contentSectionThree={
						homePageContent?.textImageJumbo?.textImageGroupThree
					}
				/>

				{/* CASE STUDIES */}
				<CaseStudies
					title={homePageContent?.caseStudies?.title}
					paragraph={homePageContent?.caseStudies?.paragraph}
					content={caseStudiesContent?.caseStudiesContent}
				/>

				{/* TESTIMONIAL */}
				<Testimonial
					// Content
					title={homePageContent?.testimonialSlider?.title}
					testimonialContent={
						homePageContent?.testimonialSlider?.testimonialContent
					}
					// Display Options
					displayBackgroundAesthetics={
						homePageContent?.testimonialSlider?.displayBackgroundAesthetics
					}
				/>

				{/* AWARDS */}
				<Awards
					title={homePageContent?.awards?.title}
					buttonLink={homePageContent?.awards?.buttonLink}
					paragraphOne={homePageContent?.awards?.paragraphOne}
					paragraphTwo={homePageContent?.awards?.paragraphTwo}
					awardsOneImage={homePageContent?.awards?.awardsOne?.sourceUrl}
					awardsTwoImage={homePageContent?.awards?.awardsTwo?.sourceUrl}
					// Display Options
					displayStylingOptions={homePageContent?.awards?.displayStylingOptions}
					displayButtonOptions={homePageContent?.awards?.displayButtonOptions}
					selectBackgroundAestheticsOptions={
						homePageContent?.awards?.selectBackgroundAestheticsOptions
					}
				/>

				{/* READ BLOGS */}
				<ReadBlogs
					title={homePageContent?.readOurBlogs?.title}
					readBlogsContent={readBlogsContent?.readBlogsContent}
				/>
			</main>

			{/* <!--===== FOOTER =====--> */}
			<Footer
				footerContent={footerContent?.footerContent}
				menuLinks={footerContent?.footerMenu}
			/>
		</>
	);
}

export async function getStaticProps() {
	const getHomePageContent = gql`
		{
			mainContent: pages(where: {id: 7}) {
				edges {
					node {
						homePage {
							titleTwoParagraphsButton {
								title
								paragraphTwo
								paragraphOne
								displayThreeSquaresOption
								displayEmailLinkOption
								displayButtonOption
								displayBoldText
								boldParagraph
								buttonLink {
									url
									title
									target
								}
							}
							textImageJumbo {
								textImageGroupTwo {
									title
									subtitle
									paragraphTwo
									paragraphOne
									image {
										sourceUrl
									}
									buttonLink {
										url
										title
										target
									}
								}
								textImageGroupThree {
									title
									subtitle
									paragraphTwo
									paragraphOne
									buttonLink {
										url
										title
										target
									}
									image {
										sourceUrl
									}
								}
								textImageGroupOne {
									title
									subtitle
									paragraphTwo
									paragraphOne
									buttonLink {
										url
										title
										target
									}
									image {
										sourceUrl
									}
								}
							}
							testimonialSlider {
								title
								displayBackgroundAestheticsOption
								testimonialContent {
									personName
									paragraph
								}
							}
							heroSection {
								title
								heroImage {
									sourceUrl
								}
							}
							contentSquares {
								title
								displayTitle
								displayNumberOfColumns
								displayBlueGreySquares
								displayBackgroundAesthetics
								column {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
								columnTwo {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
								columnThree {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
								columnFour {
									title
									paragraph
									buttonLink {
										url
										title
										target
									}
									backgroundImage {
										sourceUrl
									}
								}
							}
							caseStudies {
								title
								paragraph
							}
							awards {
								title
								selectBackgroundAestheticsOptions
								paragraphTwo
								paragraphOne
								displayStylingOptions
								displayButtonOptions
								buttonLink {
									url
									title
									target
								}
								awardsTwo {
									sourceUrl
								}
								awardsOne {
									sourceUrl
								}
							}
							readOurBlogs {
								title
							}
						}
					}
				}
			}
		}
	`;

	const response = await client.query({
		query: getHomePageContent,
	});

	const navbarContent = await getNavbarContent();
	const footerContent = await getFooterContent();
	const readBlogsContent = await getReadBlogsContent();
	const caseStudiesContent = await getCaseStudiesContent();

	return {
		props: {
			navbarContent,
			homePageContent: response?.data?.mainContent?.edges[0]?.node?.homePage,
			caseStudiesContent,
			readBlogsContent,
			footerContent,
		},
		revalidate: 1,
	};
}
